# CMake generated Testfile for 
# Source directory: C:/Users/hp/Documents/mermai-blockchain
# Build directory: C:/Users/hp/Documents/mermai-blockchain/build-cmake
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[merlite_compiler_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/merlite_compiler_test.exe")
set_tests_properties([=[merlite_compiler_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_biometric_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_biometric_test.exe")
set_tests_properties([=[mermai_biometric_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_block_validation_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_block_validation_test.exe")
set_tests_properties([=[mermai_block_validation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_cli_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_cli_test.exe")
set_tests_properties([=[mermai_cli_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_consensus_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_consensus_test.exe")
set_tests_properties([=[mermai_consensus_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_database_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_database_test.exe")
set_tests_properties([=[mermai_database_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_finality_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_finality_test.exe")
set_tests_properties([=[mermai_finality_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_governance_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_governance_test.exe")
set_tests_properties([=[mermai_governance_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_http_rpc_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_http_rpc_test.exe")
set_tests_properties([=[mermai_http_rpc_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_mempool_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_mempool_test.exe")
set_tests_properties([=[mermai_mempool_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_merkle_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_merkle_test.exe")
set_tests_properties([=[mermai_merkle_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_multi_node_sync_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_multi_node_sync_test.exe")
set_tests_properties([=[mermai_multi_node_sync_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_multisig_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_multisig_test.exe")
set_tests_properties([=[mermai_multisig_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_network_security_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_network_security_test.exe")
set_tests_properties([=[mermai_network_security_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_p2p_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_p2p_test.exe")
set_tests_properties([=[mermai_p2p_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_pubsub_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_pubsub_test.exe")
set_tests_properties([=[mermai_pubsub_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_quorum_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_quorum_test.exe")
set_tests_properties([=[mermai_quorum_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_restart_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_restart_test.exe")
set_tests_properties([=[mermai_restart_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_rewards_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_rewards_test.exe")
set_tests_properties([=[mermai_rewards_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_rpc_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_rpc_test.exe")
set_tests_properties([=[mermai_rpc_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_self_aware_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_self_aware_test.exe")
set_tests_properties([=[mermai_self_aware_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_signature_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_signature_test.exe")
set_tests_properties([=[mermai_signature_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_slashing_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_slashing_test.exe")
set_tests_properties([=[mermai_slashing_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_snapshot_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_snapshot_test.exe")
set_tests_properties([=[mermai_snapshot_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_spv_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_spv_test.exe")
set_tests_properties([=[mermai_spv_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_token_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_token_test.exe")
set_tests_properties([=[mermai_token_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
add_test([=[mermai_vm_test]=] "C:/Users/hp/Documents/mermai-blockchain/build-cmake/mermai_vm_test.exe")
set_tests_properties([=[mermai_vm_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;85;add_test;C:/Users/hp/Documents/mermai-blockchain/CMakeLists.txt;0;")
